prm:
  debug_output: false
  seed: 1                               # Seed of the visibility-PRM. Set to -1 for random!
  T: 8.0                                # Time horizon [s]
  N: 20 # 40                                 # Discrete time steps [#]
  # T: 4.0
  # N: 10
  topology_comparison: Homology         # Homology (default) or UVD
  n_samples: 10000 #200    # Number of samples for PRM
  timeout: 800 #15       # Timeout for PRM sampling [ms]
  n_paths: 4        # Number of guidance trajectories
  view_angle_times_pi: 0.606  # View angle when sampling in a conus (disabled by default)
  max_velocity: 3.0           # Maximum velocity of connections between nodes
  max_acceleration: 3.0       # Maximum velocity of connections between nodes
  selection_weights:
    consistency: 0.24904675216524505  # How much better should a new trajectory be to be selected [%]
  goals:  # Only used when `LoadReferencePath` is used to set the goals
    longitudinal: 6   # Number of goals in direction of the path
    vertical: 3       # Number of goals in direction orthogonal to the path
  visuals:
    visualize_all_samples: false    # Visualizes all PRM samples
  enable:
    dynamically_propagate_nodes: false #true  # Propagate the nodes in time (dropping them)
    project_from_obstacles: false       # Project the guidance trajectory from obstacles if enabled (not necessary by default)
  test_node:
    continuous_replanning: false #true         # When using the test nodes: keep planning continuously?
