name: ROS CI - Build Guidance Planner

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:

  industrial_ci:
      name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false # uncomment if failing jobs should not cancel the others immediately
        matrix: # matrix is the product of entries
          ROS_DISTRO: [humble]
          ROS_REPO: [main]
          # exclude: # specific configuration can be excludes
          #   - {ROS_DISTRO: melodic, ROS_REPO: testing}
          # include: # add additional configurations
            # - {ROS_DISTRO: kinetic, ROS_REPO: testing}
      # env:
      #   CCACHE_DIR: "${{ github.workspace }}/.ccache" # directory for ccache (and how we enable ccache in industrial_ci)
      steps:
        - uses: actions/checkout@v4 # clone target repository
        - uses: 'ros-industrial/industrial_ci@master' # run industrial_ci
          env: # either pass all entries explicitly
            ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
            ROS_REPO: ${{ matrix.ROS_REPO }}
            TARGET_WORKSPACE: $TARGET_REPO_PATH github:oscardegroot/ros_tools#main
            BEFORE_INSTALL_TARGET_DEPENDENCIES: cd /root/target_ws/src/guidance_planner && python3 switch_to_ros.py 2 && cd ../ros_tools && python3 switch_to_ros.py 2
              
          # with: # or pass the full matrix as config
          #    config: ${{toJSON(matrix)}}


